app:
  name: shopify
namespace: 
image:
  name: shopify
  pullPolicy: Always
  registry: cashewpayments
  tag: 1.0.0
  pullSecrets:
service:
  cpu: 2
  memory: 1G
  port: 
  replicas: 1
  type: NodePort
storage:
  mountPath: 
  size:
env:
  configmap:
    name:
  secret:
    name: ""
configmapData:
  username: 
  password:
  dbname:
ingress:
  enabled: false
  hostName: "dev.cashewpayments.com"
  path: /shopify-app
  pathType: ImplementationSpecific
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:084471643532:certificate/f1df3ec0-37ab-4e7f-aa51-3679ba9a9fad
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels: {}

