apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: shopify-api
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.app.name }}
